# Generated by Django 5.2 on 2025-05-20 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
