# Generated by Django 5.2 on 2025-06-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_producto_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='producto',
            name='numero_de_serie',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
