# Generated by Django 5.2 on 2025-05-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('creado', 'Creado'), ('editado', 'Editado'), ('deshabilitado', 'Deshabilitado')], max_length=15),
        ),
    ]
