# Generated by Django 5.2 on 2025-06-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0003_alter_movimiento_cantidad_alter_movimiento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='motivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
